included:
  - ../BitmovinConvivaAnalytics/Classes # Pod
  - ./ # Example

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules:
  - todo
  - trailing_comma

opt_in_rules:
  # performance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - reduce_into
  - sorted_first_last

  # idiomatic
  - explicit_init
  - fallthrough
  - force_unwrapping
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - redundant_nil_coalescing
  - convenience_type
  - extension_access_modifier
  - fatal_error_message
  - file_name
  - file_name_no_space
  - legacy_multiple
  - legacy_random
  - pattern_matching_keywords
  - redundant_type_annotation
  - toggle_bool
  - unavailable_function
  - xct_specific_matcher

  #lint
  - overridden_super_call
  - empty_xctest_method
  - identical_operands
  - lower_acl_than_parent
  - override_in_extension
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - unused_import
  - yoda_condition

  #style
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - implicit_return
  #  - indentation_width # causing a lot of false positives, see: https://github.com/realm/SwiftLint/issues/3046
  #  - literal_expression_end_indentation # causing error 'bus error' when running autocorrect
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_function_chains
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - single_test_class
  - sorted_imports
  - switch_case_on_newline
  - trailing_closure # in case of error 'illegal instruction: 4 swiftlint', comment this rule out, as this seems to crash SourceKit https://github.com/realm/SwiftLint/issues/2793
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

indentation_width:
  include_comments: false
deployment_target:
  iOS_deployment_target: 14.0
  tvOS_deployment_target: 14.0
line_length:
  ignores_urls: true
