def shared_pods
  pod 'BitmovinConvivaAnalytics', path: '../'
  pod 'BitmovinPlayer', git: 'https://github.com/bitmovin/bitmovin-player-ios-sdk-cocoapod.git', tag: '2.51.0'
  pod 'ConvivaSDK', '4.0.3'

  pod 'SwiftLint'
end

target 'BitmovinConvivaAnalytics_Example' do
  use_frameworks!
  platform :ios, '9.0'
  shared_pods

  pod 'GoogleAds-IMA-iOS-SDK', '3.11.1'
end

target 'BitmovinConvivaAnalytics_TvOSExample' do
  use_frameworks!
  platform :tvos, '9.0'

  shared_pods
end

target 'BitmovinConvivaAnalytics_Tests' do
  use_frameworks!
  platform :ios, '9.0'
  shared_pods

  pod 'Quick', '~> 1.3.2'
  pod 'Nimble', '~> 7.3.4'
end
