source 'https://github.com/bitmovin/cocoapod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

def shared_pods
  pod 'BitmovinConvivaAnalytics', path: '../'
  pod 'BitmovinPlayer', '3.6.1-rc.2'
  pod 'ConvivaSDK', '4.0.13'

  pod 'SwiftLint'
end

target 'BitmovinConvivaAnalytics_Example' do
  use_frameworks!
  platform :ios, '12.0'
  shared_pods

  pod 'GoogleAds-IMA-iOS-SDK', '3.12.1'
end

target 'BitmovinConvivaAnalytics_TvOSExample' do
  use_frameworks!
  platform :tvos, '12.0'

  shared_pods
end

target 'BitmovinConvivaAnalytics_Tests' do
  use_frameworks!
  platform :ios, '12.0'
  shared_pods

  pod 'Quick', '~> 4.0.0'
  pod 'Nimble', '~> 9.2.0'
end
