source 'https://github.com/bitmovin/cocoapod-specs.git'
source 'https://cdn.cocoapods.org/'

def shared_pods
  pod 'BitmovinConvivaAnalytics', path: '../'
  pod 'BitmovinPlayer', '3.63.0'
  pod 'ConvivaSDK', '4.0.49'

  pod 'SwiftLint'
end

target 'BitmovinConvivaAnalytics_Example' do
  use_frameworks!
  platform :ios, '14.0'
  shared_pods

  pod 'GoogleAds-IMA-iOS-SDK', '3.22.1'
end

target 'BitmovinConvivaAnalytics_TvOSExample' do
  use_frameworks!
  platform :tvos, '14.0'
  shared_pods

  pod 'GoogleAds-IMA-tvOS-SDK', '4.12.0'
end

target 'BitmovinConvivaAnalytics_Tests' do
  use_frameworks!
  platform :ios, '14.0'
  shared_pods

  pod 'Quick', '~> 4.0.0'
  pod 'Nimble', '~> 9.2.0'
end
