name: CI

on:
  pull_request:
    branches: ['**']
    paths-ignore:
      - '*.md'

  push:
    branches: ['**']
    paths-ignore:
      - '*.md'

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-style:
    name: Code style
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Check code style
        run: swiftlint

  tests-player:
    name: Tests
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/cache@v2
        id: cocoapods-cache
        with:
          path: Example/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: CocoaPods
        if: steps.cocoapods-cache.outputs.cache-hit != 'true'
        run: |
          cd Example && pod install

      - name: View devices
        run: xcrun simctl list devices

      - name: Tests
        run: >-
          xcodebuild test
          -workspace Example/BitmovinConvivaAnalytics.xcworkspace
          -scheme BitmovinConvivaAnalytics_Tests
          -destination 'platform=iOS Simulator,name=iPhone 14'
          -sdk iphonesimulator