name: CI

on:
  pull_request:
    branches: ['**']
    paths-ignore:
      - '*.md'

  push:
    branches: ['**']
    paths-ignore:
      - '*.md'

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests-player:
    name: Unit tests for Bitmovin Conviva Integration
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
        with:
          path: Example/Pods
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Example/Podfile.lock') }}

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: cd Example && pod install --repo-update

      - name: Unit tests
        run: pwd && xcodebuild -workspace Example/BitmovinConvivaAnalytics.xcworkspace -scheme BitmovinConvivaAnalytics_Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=Any iOS Simulator Device' test
